# Docker Compose is a tool for defining and running multi-container applications.
# Compose simplifies the control of your entire application stack, making it easy to manage services, networks, and volumes in a single, comprehensible YAML configuration file. Then, with a single command, you create and start all the services from your configuration file.
# version is basically the version of the docker compose you will be using

version: "3.8"
# services are basically projects we want the images and container for

services:
  api:
   build: ./api
   container_name: mydockerfive_c3_nodemon
   ports:
     - '4000:4000'
   volumes:
     - ./api:/app
     - ./app/node_modules